/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as StoreRouteImport } from './routes/store'
import { Route as SellRouteImport } from './routes/sell'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as MyListingsRouteImport } from './routes/my-listings'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MessagesIndexRouteImport } from './routes/messages.index'
import { Route as MarketIndexRouteImport } from './routes/market.index'
import { Route as LiveIndexRouteImport } from './routes/live.index'
import { Route as SellerUsernameRouteImport } from './routes/seller.$username'
import { Route as MessagesUserIdRouteImport } from './routes/messages.$userId'
import { Route as MarketIdRouteImport } from './routes/market.$id'
import { Route as LiveIdRouteImport } from './routes/live.$id'
import { Route as ApiPublicHooksRefreshVaultValuesRouteImport } from './routes/api/public/hooks/refresh-vault-values'

const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MyListingsRoute = MyListingsRouteImport.update({
  id: '/my-listings',
  path: '/my-listings',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketIndexRoute = MarketIndexRouteImport.update({
  id: '/market/',
  path: '/market/',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveIndexRoute = LiveIndexRouteImport.update({
  id: '/live/',
  path: '/live/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerUsernameRoute = SellerUsernameRouteImport.update({
  id: '/seller/$username',
  path: '/seller/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesUserIdRoute = MessagesUserIdRouteImport.update({
  id: '/messages/$userId',
  path: '/messages/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketIdRoute = MarketIdRouteImport.update({
  id: '/market/$id',
  path: '/market/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveIdRoute = LiveIdRouteImport.update({
  id: '/live/$id',
  path: '/live/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRefreshVaultValuesRoute =
  ApiPublicHooksRefreshVaultValuesRouteImport.update({
    id: '/api/public/hooks/refresh-vault-values',
    path: '/api/public/hooks/refresh-vault-values',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/feed': typeof FeedRoute
  '/my-listings': typeof MyListingsRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/sell': typeof SellRoute
  '/store': typeof StoreRoute
  '/vault': typeof VaultRoute
  '/live/$id': typeof LiveIdRoute
  '/market/$id': typeof MarketIdRoute
  '/messages/$userId': typeof MessagesUserIdRoute
  '/seller/$username': typeof SellerUsernameRoute
  '/live/': typeof LiveIndexRoute
  '/market/': typeof MarketIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/api/public/hooks/refresh-vault-values': typeof ApiPublicHooksRefreshVaultValuesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/feed': typeof FeedRoute
  '/my-listings': typeof MyListingsRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/sell': typeof SellRoute
  '/store': typeof StoreRoute
  '/vault': typeof VaultRoute
  '/live/$id': typeof LiveIdRoute
  '/market/$id': typeof MarketIdRoute
  '/messages/$userId': typeof MessagesUserIdRoute
  '/seller/$username': typeof SellerUsernameRoute
  '/live': typeof LiveIndexRoute
  '/market': typeof MarketIndexRoute
  '/messages': typeof MessagesIndexRoute
  '/api/public/hooks/refresh-vault-values': typeof ApiPublicHooksRefreshVaultValuesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/feed': typeof FeedRoute
  '/my-listings': typeof MyListingsRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/sell': typeof SellRoute
  '/store': typeof StoreRoute
  '/vault': typeof VaultRoute
  '/live/$id': typeof LiveIdRoute
  '/market/$id': typeof MarketIdRoute
  '/messages/$userId': typeof MessagesUserIdRoute
  '/seller/$username': typeof SellerUsernameRoute
  '/live/': typeof LiveIndexRoute
  '/market/': typeof MarketIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/api/public/hooks/refresh-vault-values': typeof ApiPublicHooksRefreshVaultValuesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/feed'
    | '/my-listings'
    | '/orders'
    | '/profile'
    | '/sell'
    | '/store'
    | '/vault'
    | '/live/$id'
    | '/market/$id'
    | '/messages/$userId'
    | '/seller/$username'
    | '/live/'
    | '/market/'
    | '/messages/'
    | '/api/public/hooks/refresh-vault-values'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/feed'
    | '/my-listings'
    | '/orders'
    | '/profile'
    | '/sell'
    | '/store'
    | '/vault'
    | '/live/$id'
    | '/market/$id'
    | '/messages/$userId'
    | '/seller/$username'
    | '/live'
    | '/market'
    | '/messages'
    | '/api/public/hooks/refresh-vault-values'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/feed'
    | '/my-listings'
    | '/orders'
    | '/profile'
    | '/sell'
    | '/store'
    | '/vault'
    | '/live/$id'
    | '/market/$id'
    | '/messages/$userId'
    | '/seller/$username'
    | '/live/'
    | '/market/'
    | '/messages/'
    | '/api/public/hooks/refresh-vault-values'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  FeedRoute: typeof FeedRoute
  MyListingsRoute: typeof MyListingsRoute
  OrdersRoute: typeof OrdersRoute
  ProfileRoute: typeof ProfileRoute
  SellRoute: typeof SellRoute
  StoreRoute: typeof StoreRoute
  VaultRoute: typeof VaultRoute
  LiveIdRoute: typeof LiveIdRoute
  MarketIdRoute: typeof MarketIdRoute
  MessagesUserIdRoute: typeof MessagesUserIdRoute
  SellerUsernameRoute: typeof SellerUsernameRoute
  LiveIndexRoute: typeof LiveIndexRoute
  MarketIndexRoute: typeof MarketIndexRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
  ApiPublicHooksRefreshVaultValuesRoute: typeof ApiPublicHooksRefreshVaultValuesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-listings': {
      id: '/my-listings'
      path: '/my-listings'
      fullPath: '/my-listings'
      preLoaderRoute: typeof MyListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market/': {
      id: '/market/'
      path: '/market'
      fullPath: '/market/'
      preLoaderRoute: typeof MarketIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/': {
      id: '/live/'
      path: '/live'
      fullPath: '/live/'
      preLoaderRoute: typeof LiveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/$username': {
      id: '/seller/$username'
      path: '/seller/$username'
      fullPath: '/seller/$username'
      preLoaderRoute: typeof SellerUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$userId': {
      id: '/messages/$userId'
      path: '/messages/$userId'
      fullPath: '/messages/$userId'
      preLoaderRoute: typeof MessagesUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market/$id': {
      id: '/market/$id'
      path: '/market/$id'
      fullPath: '/market/$id'
      preLoaderRoute: typeof MarketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/$id': {
      id: '/live/$id'
      path: '/live/$id'
      fullPath: '/live/$id'
      preLoaderRoute: typeof LiveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/refresh-vault-values': {
      id: '/api/public/hooks/refresh-vault-values'
      path: '/api/public/hooks/refresh-vault-values'
      fullPath: '/api/public/hooks/refresh-vault-values'
      preLoaderRoute: typeof ApiPublicHooksRefreshVaultValuesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  FeedRoute: FeedRoute,
  MyListingsRoute: MyListingsRoute,
  OrdersRoute: OrdersRoute,
  ProfileRoute: ProfileRoute,
  SellRoute: SellRoute,
  StoreRoute: StoreRoute,
  VaultRoute: VaultRoute,
  LiveIdRoute: LiveIdRoute,
  MarketIdRoute: MarketIdRoute,
  MessagesUserIdRoute: MessagesUserIdRoute,
  SellerUsernameRoute: SellerUsernameRoute,
  LiveIndexRoute: LiveIndexRoute,
  MarketIndexRoute: MarketIndexRoute,
  MessagesIndexRoute: MessagesIndexRoute,
  ApiPublicHooksRefreshVaultValuesRoute: ApiPublicHooksRefreshVaultValuesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
