/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as TutorialsRouteImport } from './routes/tutorials'
import { Route as SupportRouteImport } from './routes/support'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as StoreRouteImport } from './routes/store'
import { Route as ShowoffRouteImport } from './routes/showoff'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SellRouteImport } from './routes/sell'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PayoutsRouteImport } from './routes/payouts'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ObsHubRouteImport } from './routes/obs-hub'
import { Route as MyListingsRouteImport } from './routes/my-listings'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as DisputesRouteImport } from './routes/disputes'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MessagesIndexRouteImport } from './routes/messages.index'
import { Route as MarketIndexRouteImport } from './routes/market.index'
import { Route as LiveIndexRouteImport } from './routes/live.index'
import { Route as StudioIdRouteImport } from './routes/studio.$id'
import { Route as SellerUsernameRouteImport } from './routes/seller.$username'
import { Route as MessagesUserIdRouteImport } from './routes/messages.$userId'
import { Route as MarketIdRouteImport } from './routes/market.$id'
import { Route as LiveIdRouteImport } from './routes/live.$id'
import { Route as LegalTosRouteImport } from './routes/legal.tos'
import { Route as LegalSellerHostAgreementRouteImport } from './routes/legal.seller-host-agreement'
import { Route as LegalSellerAgreementRouteImport } from './routes/legal.seller-agreement'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalCommunityGuidelinesRouteImport } from './routes/legal.community-guidelines'
import { Route as LegalBuyerTermsRouteImport } from './routes/legal.buyer-terms'
import { Route as AdminPerformanceRouteImport } from './routes/admin_.performance'
import { Route as AdminRecoveryRouteImport } from './routes/admin.recovery'
import { Route as JoinCamStreamIdTokenRouteImport } from './routes/join-cam.$streamId.$token'
import { Route as ApiPublicBetaVerifyRouteImport } from './routes/api/public/beta-verify'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe/webhook'
import { Route as ApiPublicHooksSyncTcgcsvRouteImport } from './routes/api/public/hooks/sync-tcgcsv'
import { Route as ApiPublicHooksShowRemindersRouteImport } from './routes/api/public/hooks/show-reminders'
import { Route as ApiPublicHooksRefreshVaultValuesRouteImport } from './routes/api/public/hooks/refresh-vault-values'

const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialsRoute = TutorialsRouteImport.update({
  id: '/tutorials',
  path: '/tutorials',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowoffRoute = ShowoffRouteImport.update({
  id: '/showoff',
  path: '/showoff',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PayoutsRoute = PayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ObsHubRoute = ObsHubRouteImport.update({
  id: '/obs-hub',
  path: '/obs-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const MyListingsRoute = MyListingsRouteImport.update({
  id: '/my-listings',
  path: '/my-listings',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const DisputesRoute = DisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketIndexRoute = MarketIndexRouteImport.update({
  id: '/market/',
  path: '/market/',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveIndexRoute = LiveIndexRouteImport.update({
  id: '/live/',
  path: '/live/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIdRoute = StudioIdRouteImport.update({
  id: '/studio/$id',
  path: '/studio/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerUsernameRoute = SellerUsernameRouteImport.update({
  id: '/seller/$username',
  path: '/seller/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesUserIdRoute = MessagesUserIdRouteImport.update({
  id: '/messages/$userId',
  path: '/messages/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketIdRoute = MarketIdRouteImport.update({
  id: '/market/$id',
  path: '/market/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveIdRoute = LiveIdRouteImport.update({
  id: '/live/$id',
  path: '/live/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTosRoute = LegalTosRouteImport.update({
  id: '/legal/tos',
  path: '/legal/tos',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSellerHostAgreementRoute =
  LegalSellerHostAgreementRouteImport.update({
    id: '/legal/seller-host-agreement',
    path: '/legal/seller-host-agreement',
    getParentRoute: () => rootRouteImport,
  } as any)
const LegalSellerAgreementRoute = LegalSellerAgreementRouteImport.update({
  id: '/legal/seller-agreement',
  path: '/legal/seller-agreement',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCommunityGuidelinesRoute =
  LegalCommunityGuidelinesRouteImport.update({
    id: '/legal/community-guidelines',
    path: '/legal/community-guidelines',
    getParentRoute: () => rootRouteImport,
  } as any)
const LegalBuyerTermsRoute = LegalBuyerTermsRouteImport.update({
  id: '/legal/buyer-terms',
  path: '/legal/buyer-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPerformanceRoute = AdminPerformanceRouteImport.update({
  id: '/admin_/performance',
  path: '/admin/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRecoveryRoute = AdminRecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => AdminRoute,
} as any)
const JoinCamStreamIdTokenRoute = JoinCamStreamIdTokenRouteImport.update({
  id: '/join-cam/$streamId/$token',
  path: '/join-cam/$streamId/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBetaVerifyRoute = ApiPublicBetaVerifyRouteImport.update({
  id: '/api/public/beta-verify',
  path: '/api/public/beta-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe/webhook',
  path: '/api/public/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSyncTcgcsvRoute =
  ApiPublicHooksSyncTcgcsvRouteImport.update({
    id: '/api/public/hooks/sync-tcgcsv',
    path: '/api/public/hooks/sync-tcgcsv',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksShowRemindersRoute =
  ApiPublicHooksShowRemindersRouteImport.update({
    id: '/api/public/hooks/show-reminders',
    path: '/api/public/hooks/show-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRefreshVaultValuesRoute =
  ApiPublicHooksRefreshVaultValuesRouteImport.update({
    id: '/api/public/hooks/refresh-vault-values',
    path: '/api/public/hooks/refresh-vault-values',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/bookmarks': typeof BookmarksRoute
  '/cart': typeof CartRoute
  '/discover': typeof DiscoverRoute
  '/disputes': typeof DisputesRoute
  '/feed': typeof FeedRoute
  '/my-listings': typeof MyListingsRoute
  '/obs-hub': typeof ObsHubRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRoute
  '/payouts': typeof PayoutsRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sell': typeof SellRoute
  '/settings': typeof SettingsRoute
  '/showoff': typeof ShowoffRoute
  '/store': typeof StoreRoute
  '/stories': typeof StoriesRoute
  '/support': typeof SupportRoute
  '/tutorials': typeof TutorialsRoute
  '/vault': typeof VaultRoute
  '/admin/recovery': typeof AdminRecoveryRoute
  '/admin/performance': typeof AdminPerformanceRoute
  '/legal/buyer-terms': typeof LegalBuyerTermsRoute
  '/legal/community-guidelines': typeof LegalCommunityGuidelinesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/seller-agreement': typeof LegalSellerAgreementRoute
  '/legal/seller-host-agreement': typeof LegalSellerHostAgreementRoute
  '/legal/tos': typeof LegalTosRoute
  '/live/$id': typeof LiveIdRoute
  '/market/$id': typeof MarketIdRoute
  '/messages/$userId': typeof MessagesUserIdRoute
  '/seller/$username': typeof SellerUsernameRoute
  '/studio/$id': typeof StudioIdRoute
  '/live/': typeof LiveIndexRoute
  '/market/': typeof MarketIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/api/public/beta-verify': typeof ApiPublicBetaVerifyRoute
  '/join-cam/$streamId/$token': typeof JoinCamStreamIdTokenRoute
  '/api/public/hooks/refresh-vault-values': typeof ApiPublicHooksRefreshVaultValuesRoute
  '/api/public/hooks/show-reminders': typeof ApiPublicHooksShowRemindersRoute
  '/api/public/hooks/sync-tcgcsv': typeof ApiPublicHooksSyncTcgcsvRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/bookmarks': typeof BookmarksRoute
  '/cart': typeof CartRoute
  '/discover': typeof DiscoverRoute
  '/disputes': typeof DisputesRoute
  '/feed': typeof FeedRoute
  '/my-listings': typeof MyListingsRoute
  '/obs-hub': typeof ObsHubRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRoute
  '/payouts': typeof PayoutsRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sell': typeof SellRoute
  '/settings': typeof SettingsRoute
  '/showoff': typeof ShowoffRoute
  '/store': typeof StoreRoute
  '/stories': typeof StoriesRoute
  '/support': typeof SupportRoute
  '/tutorials': typeof TutorialsRoute
  '/vault': typeof VaultRoute
  '/admin/recovery': typeof AdminRecoveryRoute
  '/admin/performance': typeof AdminPerformanceRoute
  '/legal/buyer-terms': typeof LegalBuyerTermsRoute
  '/legal/community-guidelines': typeof LegalCommunityGuidelinesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/seller-agreement': typeof LegalSellerAgreementRoute
  '/legal/seller-host-agreement': typeof LegalSellerHostAgreementRoute
  '/legal/tos': typeof LegalTosRoute
  '/live/$id': typeof LiveIdRoute
  '/market/$id': typeof MarketIdRoute
  '/messages/$userId': typeof MessagesUserIdRoute
  '/seller/$username': typeof SellerUsernameRoute
  '/studio/$id': typeof StudioIdRoute
  '/live': typeof LiveIndexRoute
  '/market': typeof MarketIndexRoute
  '/messages': typeof MessagesIndexRoute
  '/api/public/beta-verify': typeof ApiPublicBetaVerifyRoute
  '/join-cam/$streamId/$token': typeof JoinCamStreamIdTokenRoute
  '/api/public/hooks/refresh-vault-values': typeof ApiPublicHooksRefreshVaultValuesRoute
  '/api/public/hooks/show-reminders': typeof ApiPublicHooksShowRemindersRoute
  '/api/public/hooks/sync-tcgcsv': typeof ApiPublicHooksSyncTcgcsvRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/bookmarks': typeof BookmarksRoute
  '/cart': typeof CartRoute
  '/discover': typeof DiscoverRoute
  '/disputes': typeof DisputesRoute
  '/feed': typeof FeedRoute
  '/my-listings': typeof MyListingsRoute
  '/obs-hub': typeof ObsHubRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRoute
  '/payouts': typeof PayoutsRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sell': typeof SellRoute
  '/settings': typeof SettingsRoute
  '/showoff': typeof ShowoffRoute
  '/store': typeof StoreRoute
  '/stories': typeof StoriesRoute
  '/support': typeof SupportRoute
  '/tutorials': typeof TutorialsRoute
  '/vault': typeof VaultRoute
  '/admin/recovery': typeof AdminRecoveryRoute
  '/admin_/performance': typeof AdminPerformanceRoute
  '/legal/buyer-terms': typeof LegalBuyerTermsRoute
  '/legal/community-guidelines': typeof LegalCommunityGuidelinesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/seller-agreement': typeof LegalSellerAgreementRoute
  '/legal/seller-host-agreement': typeof LegalSellerHostAgreementRoute
  '/legal/tos': typeof LegalTosRoute
  '/live/$id': typeof LiveIdRoute
  '/market/$id': typeof MarketIdRoute
  '/messages/$userId': typeof MessagesUserIdRoute
  '/seller/$username': typeof SellerUsernameRoute
  '/studio/$id': typeof StudioIdRoute
  '/live/': typeof LiveIndexRoute
  '/market/': typeof MarketIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/api/public/beta-verify': typeof ApiPublicBetaVerifyRoute
  '/join-cam/$streamId/$token': typeof JoinCamStreamIdTokenRoute
  '/api/public/hooks/refresh-vault-values': typeof ApiPublicHooksRefreshVaultValuesRoute
  '/api/public/hooks/show-reminders': typeof ApiPublicHooksShowRemindersRoute
  '/api/public/hooks/sync-tcgcsv': typeof ApiPublicHooksSyncTcgcsvRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/bookmarks'
    | '/cart'
    | '/discover'
    | '/disputes'
    | '/feed'
    | '/my-listings'
    | '/obs-hub'
    | '/onboarding'
    | '/orders'
    | '/payouts'
    | '/profile'
    | '/reset-password'
    | '/sell'
    | '/settings'
    | '/showoff'
    | '/store'
    | '/stories'
    | '/support'
    | '/tutorials'
    | '/vault'
    | '/admin/recovery'
    | '/admin/performance'
    | '/legal/buyer-terms'
    | '/legal/community-guidelines'
    | '/legal/privacy'
    | '/legal/seller-agreement'
    | '/legal/seller-host-agreement'
    | '/legal/tos'
    | '/live/$id'
    | '/market/$id'
    | '/messages/$userId'
    | '/seller/$username'
    | '/studio/$id'
    | '/live/'
    | '/market/'
    | '/messages/'
    | '/api/public/beta-verify'
    | '/join-cam/$streamId/$token'
    | '/api/public/hooks/refresh-vault-values'
    | '/api/public/hooks/show-reminders'
    | '/api/public/hooks/sync-tcgcsv'
    | '/api/public/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/bookmarks'
    | '/cart'
    | '/discover'
    | '/disputes'
    | '/feed'
    | '/my-listings'
    | '/obs-hub'
    | '/onboarding'
    | '/orders'
    | '/payouts'
    | '/profile'
    | '/reset-password'
    | '/sell'
    | '/settings'
    | '/showoff'
    | '/store'
    | '/stories'
    | '/support'
    | '/tutorials'
    | '/vault'
    | '/admin/recovery'
    | '/admin/performance'
    | '/legal/buyer-terms'
    | '/legal/community-guidelines'
    | '/legal/privacy'
    | '/legal/seller-agreement'
    | '/legal/seller-host-agreement'
    | '/legal/tos'
    | '/live/$id'
    | '/market/$id'
    | '/messages/$userId'
    | '/seller/$username'
    | '/studio/$id'
    | '/live'
    | '/market'
    | '/messages'
    | '/api/public/beta-verify'
    | '/join-cam/$streamId/$token'
    | '/api/public/hooks/refresh-vault-values'
    | '/api/public/hooks/show-reminders'
    | '/api/public/hooks/sync-tcgcsv'
    | '/api/public/stripe/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/bookmarks'
    | '/cart'
    | '/discover'
    | '/disputes'
    | '/feed'
    | '/my-listings'
    | '/obs-hub'
    | '/onboarding'
    | '/orders'
    | '/payouts'
    | '/profile'
    | '/reset-password'
    | '/sell'
    | '/settings'
    | '/showoff'
    | '/store'
    | '/stories'
    | '/support'
    | '/tutorials'
    | '/vault'
    | '/admin/recovery'
    | '/admin_/performance'
    | '/legal/buyer-terms'
    | '/legal/community-guidelines'
    | '/legal/privacy'
    | '/legal/seller-agreement'
    | '/legal/seller-host-agreement'
    | '/legal/tos'
    | '/live/$id'
    | '/market/$id'
    | '/messages/$userId'
    | '/seller/$username'
    | '/studio/$id'
    | '/live/'
    | '/market/'
    | '/messages/'
    | '/api/public/beta-verify'
    | '/join-cam/$streamId/$token'
    | '/api/public/hooks/refresh-vault-values'
    | '/api/public/hooks/show-reminders'
    | '/api/public/hooks/sync-tcgcsv'
    | '/api/public/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  BookmarksRoute: typeof BookmarksRoute
  CartRoute: typeof CartRoute
  DiscoverRoute: typeof DiscoverRoute
  DisputesRoute: typeof DisputesRoute
  FeedRoute: typeof FeedRoute
  MyListingsRoute: typeof MyListingsRoute
  ObsHubRoute: typeof ObsHubRoute
  OnboardingRoute: typeof OnboardingRoute
  OrdersRoute: typeof OrdersRoute
  PayoutsRoute: typeof PayoutsRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SellRoute: typeof SellRoute
  SettingsRoute: typeof SettingsRoute
  ShowoffRoute: typeof ShowoffRoute
  StoreRoute: typeof StoreRoute
  StoriesRoute: typeof StoriesRoute
  SupportRoute: typeof SupportRoute
  TutorialsRoute: typeof TutorialsRoute
  VaultRoute: typeof VaultRoute
  AdminPerformanceRoute: typeof AdminPerformanceRoute
  LegalBuyerTermsRoute: typeof LegalBuyerTermsRoute
  LegalCommunityGuidelinesRoute: typeof LegalCommunityGuidelinesRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalSellerAgreementRoute: typeof LegalSellerAgreementRoute
  LegalSellerHostAgreementRoute: typeof LegalSellerHostAgreementRoute
  LegalTosRoute: typeof LegalTosRoute
  LiveIdRoute: typeof LiveIdRoute
  MarketIdRoute: typeof MarketIdRoute
  MessagesUserIdRoute: typeof MessagesUserIdRoute
  SellerUsernameRoute: typeof SellerUsernameRoute
  StudioIdRoute: typeof StudioIdRoute
  LiveIndexRoute: typeof LiveIndexRoute
  MarketIndexRoute: typeof MarketIndexRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
  ApiPublicBetaVerifyRoute: typeof ApiPublicBetaVerifyRoute
  JoinCamStreamIdTokenRoute: typeof JoinCamStreamIdTokenRoute
  ApiPublicHooksRefreshVaultValuesRoute: typeof ApiPublicHooksRefreshVaultValuesRoute
  ApiPublicHooksShowRemindersRoute: typeof ApiPublicHooksShowRemindersRoute
  ApiPublicHooksSyncTcgcsvRoute: typeof ApiPublicHooksSyncTcgcsvRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorials': {
      id: '/tutorials'
      path: '/tutorials'
      fullPath: '/tutorials'
      preLoaderRoute: typeof TutorialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showoff': {
      id: '/showoff'
      path: '/showoff'
      fullPath: '/showoff'
      preLoaderRoute: typeof ShowoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payouts': {
      id: '/payouts'
      path: '/payouts'
      fullPath: '/payouts'
      preLoaderRoute: typeof PayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obs-hub': {
      id: '/obs-hub'
      path: '/obs-hub'
      fullPath: '/obs-hub'
      preLoaderRoute: typeof ObsHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-listings': {
      id: '/my-listings'
      path: '/my-listings'
      fullPath: '/my-listings'
      preLoaderRoute: typeof MyListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disputes': {
      id: '/disputes'
      path: '/disputes'
      fullPath: '/disputes'
      preLoaderRoute: typeof DisputesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market/': {
      id: '/market/'
      path: '/market'
      fullPath: '/market/'
      preLoaderRoute: typeof MarketIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/': {
      id: '/live/'
      path: '/live'
      fullPath: '/live/'
      preLoaderRoute: typeof LiveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/$id': {
      id: '/studio/$id'
      path: '/studio/$id'
      fullPath: '/studio/$id'
      preLoaderRoute: typeof StudioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/$username': {
      id: '/seller/$username'
      path: '/seller/$username'
      fullPath: '/seller/$username'
      preLoaderRoute: typeof SellerUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$userId': {
      id: '/messages/$userId'
      path: '/messages/$userId'
      fullPath: '/messages/$userId'
      preLoaderRoute: typeof MessagesUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market/$id': {
      id: '/market/$id'
      path: '/market/$id'
      fullPath: '/market/$id'
      preLoaderRoute: typeof MarketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/$id': {
      id: '/live/$id'
      path: '/live/$id'
      fullPath: '/live/$id'
      preLoaderRoute: typeof LiveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/tos': {
      id: '/legal/tos'
      path: '/legal/tos'
      fullPath: '/legal/tos'
      preLoaderRoute: typeof LegalTosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/seller-host-agreement': {
      id: '/legal/seller-host-agreement'
      path: '/legal/seller-host-agreement'
      fullPath: '/legal/seller-host-agreement'
      preLoaderRoute: typeof LegalSellerHostAgreementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/seller-agreement': {
      id: '/legal/seller-agreement'
      path: '/legal/seller-agreement'
      fullPath: '/legal/seller-agreement'
      preLoaderRoute: typeof LegalSellerAgreementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/community-guidelines': {
      id: '/legal/community-guidelines'
      path: '/legal/community-guidelines'
      fullPath: '/legal/community-guidelines'
      preLoaderRoute: typeof LegalCommunityGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/buyer-terms': {
      id: '/legal/buyer-terms'
      path: '/legal/buyer-terms'
      fullPath: '/legal/buyer-terms'
      preLoaderRoute: typeof LegalBuyerTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/performance': {
      id: '/admin_/performance'
      path: '/admin/performance'
      fullPath: '/admin/performance'
      preLoaderRoute: typeof AdminPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/recovery': {
      id: '/admin/recovery'
      path: '/recovery'
      fullPath: '/admin/recovery'
      preLoaderRoute: typeof AdminRecoveryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/join-cam/$streamId/$token': {
      id: '/join-cam/$streamId/$token'
      path: '/join-cam/$streamId/$token'
      fullPath: '/join-cam/$streamId/$token'
      preLoaderRoute: typeof JoinCamStreamIdTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/beta-verify': {
      id: '/api/public/beta-verify'
      path: '/api/public/beta-verify'
      fullPath: '/api/public/beta-verify'
      preLoaderRoute: typeof ApiPublicBetaVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe/webhook': {
      id: '/api/public/stripe/webhook'
      path: '/api/public/stripe/webhook'
      fullPath: '/api/public/stripe/webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-tcgcsv': {
      id: '/api/public/hooks/sync-tcgcsv'
      path: '/api/public/hooks/sync-tcgcsv'
      fullPath: '/api/public/hooks/sync-tcgcsv'
      preLoaderRoute: typeof ApiPublicHooksSyncTcgcsvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/show-reminders': {
      id: '/api/public/hooks/show-reminders'
      path: '/api/public/hooks/show-reminders'
      fullPath: '/api/public/hooks/show-reminders'
      preLoaderRoute: typeof ApiPublicHooksShowRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/refresh-vault-values': {
      id: '/api/public/hooks/refresh-vault-values'
      path: '/api/public/hooks/refresh-vault-values'
      fullPath: '/api/public/hooks/refresh-vault-values'
      preLoaderRoute: typeof ApiPublicHooksRefreshVaultValuesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminRecoveryRoute: typeof AdminRecoveryRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminRecoveryRoute: AdminRecoveryRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  BookmarksRoute: BookmarksRoute,
  CartRoute: CartRoute,
  DiscoverRoute: DiscoverRoute,
  DisputesRoute: DisputesRoute,
  FeedRoute: FeedRoute,
  MyListingsRoute: MyListingsRoute,
  ObsHubRoute: ObsHubRoute,
  OnboardingRoute: OnboardingRoute,
  OrdersRoute: OrdersRoute,
  PayoutsRoute: PayoutsRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SellRoute: SellRoute,
  SettingsRoute: SettingsRoute,
  ShowoffRoute: ShowoffRoute,
  StoreRoute: StoreRoute,
  StoriesRoute: StoriesRoute,
  SupportRoute: SupportRoute,
  TutorialsRoute: TutorialsRoute,
  VaultRoute: VaultRoute,
  AdminPerformanceRoute: AdminPerformanceRoute,
  LegalBuyerTermsRoute: LegalBuyerTermsRoute,
  LegalCommunityGuidelinesRoute: LegalCommunityGuidelinesRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalSellerAgreementRoute: LegalSellerAgreementRoute,
  LegalSellerHostAgreementRoute: LegalSellerHostAgreementRoute,
  LegalTosRoute: LegalTosRoute,
  LiveIdRoute: LiveIdRoute,
  MarketIdRoute: MarketIdRoute,
  MessagesUserIdRoute: MessagesUserIdRoute,
  SellerUsernameRoute: SellerUsernameRoute,
  StudioIdRoute: StudioIdRoute,
  LiveIndexRoute: LiveIndexRoute,
  MarketIndexRoute: MarketIndexRoute,
  MessagesIndexRoute: MessagesIndexRoute,
  ApiPublicBetaVerifyRoute: ApiPublicBetaVerifyRoute,
  JoinCamStreamIdTokenRoute: JoinCamStreamIdTokenRoute,
  ApiPublicHooksRefreshVaultValuesRoute: ApiPublicHooksRefreshVaultValuesRoute,
  ApiPublicHooksShowRemindersRoute: ApiPublicHooksShowRemindersRoute,
  ApiPublicHooksSyncTcgcsvRoute: ApiPublicHooksSyncTcgcsvRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
